<a href="https://colab.research.google.com/github/ashfiya-06/STATML_2303A52366/blob/main/2303A52366statml_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1:

Imagine you are developing a simple machine learning model to predict whether a student will pass a course based on the following five features:

Study Hours per Week: Number of hours the student studies per week. Class Attendance (%): Percentage of classes attended by the student. Previous Exam Score (%): Score in the previous exam. Participation in Group Study: Whether the student participates in group study sessions (1 for Yes, 0 for No). Submission of Assignments (%): Percentage of assignments submitted by the student. Dataset

Below is an example dataset with 10 students (rows), 5 features, and a binary target label (Pass/Fail). The target label is 1 if the student is predicted to pass, and 0 if they are predicted to fail.

In [1]:
import pandas as pd
data = [[10, 90, 85, 1, 100, 1],
        [5, 60, 70, 0, 80, 0],
        [15, 95, 90, 1, 100, 1],
        [2, 30, 50, 0, 40, 0],
        [12, 85, 88, 1, 90, 1],
        [8, 75, 65, 0, 70, 0],
        [14, 92, 93, 1, 95, 1],
        [3, 50, 55, 0, 60, 0],
        [11, 88, 80, 1, 85, 1],
        [6, 65, 60, 0, 75, 0]]
df = pd.DataFrame(data, columns=['Study Hours per Week', 'Class Attendance (%)', 'Previous Exam Score (%)', 'Participation in Group Study', 'Submission of Assignments (%)', 'Pass/Fail'])
df



Study Hours per Week  Class Attendance (%)  Previous Exam Score (%)  \
0                    10                    90                       85   
1                     5                    60                       70   
2                    15                    95                       90   
3                     2                    30                       50   
4                    12                    85                       88   
5                     8                    75                       65   
6                    14                    92                       93   
7                     3                    50                       55   
8                    11                    88                       80   
9                     6                    65                       60   

   Participation in Group Study  Submission of Assignments (%)  Pass/Fail  
0                             1                            100          1  
1                             0                             80          0  
2                             1                            100          1  
3                             0                             40          0  
4                             1                             90          1  
5                             0                             70          0  
6                             1                             95          1  
7                             0                             60          0  
8                             1                             85          1  
9                             0                             75          0

In [3]:
df.to_csv('student_data.csv', index=False)
df = pd.read_csv('student_data.csv')
df


Study Hours per Week  Class Attendance (%)  Previous Exam Score (%)  \
0                    10                    90                       85   
1                     5                    60                       70   
2                    15                    95                       90   
3                     2                    30                       50   
4                    12                    85                       88   
5                     8                    75                       65   
6                    14                    92                       93   
7                     3                    50                       55   
8                    11                    88                       80   
9                     6                    65                       60   

   Participation in Group Study  Submission of Assignments (%)  Pass/Fail  
0                             1                            100          1  
1                             0                             80          0  
2                             1                            100          1  
3                             0                             40          0  
4                             1                             90          1  
5                             0                             70          0  
6                             1                             95          1  
7                             0                             60          0  
8                             1                             85          1  
9                             0                             75          0

In [4]:
x=df.drop('Pass/Fail',axis=1)
y=df['Pass/Fail']

In [5]:
import numpy as np
list=[2.0,3.0,7.0,1.0,5.0]
weight = np.array(list)
weight

array([2., 3., 7., 1., 5.])

In [6]:
def update(p,e,i):
  for j in range(len(weight)):
    weight[j]=weight[j]+p*e*float(x.iloc[i:i+1,j:j+1].values)

In [8]:
print(x.iloc[0:1,1:2])

   Class Attendance (%)
0                    90


In [9]:
learning_rate = 0.001
def error(yp,i):
  e=y[i]-yp
  if(e!=0):
    update(learning_rate,e,i)

In [10]:
yp=-1
import numpy as np
for k in range(6):
  for i in range (len(x)):
    z=np.dot(x[i:i+1],weight)
    if z>0:
      yp=1
    else:
      yp=0
    error(yp,i)
#print(yp)

<ipython-input-6-3d67c18ae89d>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  weight[j]=weight[j]+p*e*float(x.iloc[i:i+1,j:j+1].values)


In [11]:
print("Trained Weights:", weight)

# Prediction Function
def perceptron_predict(x, weights):
    z = np.dot(x, weights)
    return 1 if z >= 0 else 0

# Test the model
correct_predictions = 0
for i in range(len(x)):
    prediction = perceptron_predict(x[i:i+1], weight)
    if prediction == y[i]:
        correct_predictions += 1

# Accuracy calculation
accuracy = correct_predictions / len(x)
print(f"Accuracy: {accuracy * 100:.2f}%")

Trained Weights: [1.856 1.32  5.2   1.    3.05 ]
Accuracy: 50.00%


QUESTION 2

In [23]:
import pandas as pd
diabetes=pd.read_csv('/content/archive (1).zip')
diabetes

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [24]:
target=diabetes['class']
target

0      Positive
1      Positive
2      Positive
3      Positive
4      Positive
         ...   
515    Positive
516    Positive
517    Positive
518    Negative
519    Negative
Name: class, Length: 520, dtype: object

In [25]:
features=diabetes.drop('class',axis=1)
features

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity  
0                No              Yes      Yes     Yes  
1               Yes               No      Yes      No  
2                No              Yes      Yes      No  
3                No               No       No      No  
4               Yes              Yes      Yes     Yes  
..              ...              ...      ...     ...  
515             Yes               No       No      No  
516             Yes               No       No      No  
517             Yes              Yes       No     Yes  
518              No               No      Yes      No  
519              No               No       No      No  

[520 rows x 16 columns]

In [26]:
one_values = ["Male", "Yes"]
zero_values = ["Female","No"]

for column in features.columns:
    features[column] = features[column].replace(to_replace=one_values, value=1)
    features[column] = features[column].replace(to_replace=zero_values, value=0)
features

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  
0                  1                0                 1         1        1  
1                  0                1                 0         1        0  
2                  1                0                 1         1        0  
3                  1                0                 0         0        0  
4                  1                1                 1         1        1  
..               ...              ...               ...       ...      ...  
515                1                1                 0         0        0  
516                1                1                 0         0        0  
517                0                1                 1         0        1  
518                1                0                 0         1        0  
519                0                0                 0         0        0  

[520 rows x 16 columns]

In [27]:
one_values = ["Positive"]
zero_values = ["Negative"]

target = target.replace(to_replace=one_values, value=1)
target= target.replace(to_replace=zero_values, value=0)
target.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [28]:
import numpy as np
list1 = [0.21, 0.60, 0.78, 0.22, 0.62 ,
       0.53, 0.39, 0.036, 0.04 , 0.87,
       0.89, 0.13, 0.79, 0.13, 0.50,
       0.80]
weights=np.array(list1)
weights

array([0.21 , 0.6  , 0.78 , 0.22 , 0.62 , 0.53 , 0.39 , 0.036, 0.04 ,
       0.87 , 0.89 , 0.13 , 0.79 , 0.13 , 0.5  , 0.8  ])

In [29]:
features.iloc[0:1].values

array([[40,  1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1]])

In [30]:
pd.array([[40,  1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  1,  0,  1,  1,  1]])

<NumpyExtensionArray>
[[40, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1]]
Length: 1, dtype: object

In [31]:
def update(p,e,i):
  for j in range(len(weights)):
    weights[j]=weights[j]+p*e*float(features.iloc[i:i+1,j:j+1].values)

In [32]:
learning_rate = 0.001
def error(yp,i):
  e=target[i]-yp
  if(e!=0):
    update(learning_rate,e,i)
  return yp

In [33]:
yp=-1
import numpy as np
for k in range(6):
  for i in range (len(features)):
    z=np.dot(features[i:i+1],weights)
    if z>0:
      yp=1
    else:
      yp=0
    error(yp,i)

<ipython-input-31-19e2523c4990>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  weights[j]=weights[j]+p*e*float(features.iloc[i:i+1,j:j+1].values)


In [34]:
weights

array([-0.039,  0.517,  0.823,  0.298,  0.649,  0.54 ,  0.379,  0.03 ,
        0.041,  0.781,  0.881,  0.083,  0.822,  0.087,  0.429,  0.797])

In [35]:
print("Trained Weights:", weights)

Trained Weights: [-0.039  0.517  0.823  0.298  0.649  0.54   0.379  0.03   0.041  0.781
  0.881  0.083  0.822  0.087  0.429  0.797]


In [36]:
# Prediction Function
def perceptron_predict(x, weights):
    z = np.dot(x, weights)
    return 1 if z >= 0 else 0

# Test the model
correct_predictions = 0
for i in range(len(features)):
    prediction = perceptron_predict(features[i:i+1], weights)
    if prediction == target[i]:
        correct_predictions += 1

# Accuracy calculation
accuracy = correct_predictions / len(features)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 74.04%
